language: java

before_install:
 - chmod +x mvnw

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      addons: {apt: {packages: [oracle-java8-installer]}}
      dist: trusty
    - os: linux
      jdk: openjdk8
      dist: trusty
    - os: osx
      osx_image: xcode8.3

sudo: false

script:
 - ./mvnw install -Prelease -DskipTests=true -B -V
 - ./mvnw test
 - ./mvnw clean package -DskipTests=true
